services:
  app:
    environment:
      # Claude Code configuration
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-opus-4-20250514}

      # Serena MCP configuration
      - SERENA_MCP_PORT=${SERENA_MCP_PORT:-3000}
      - SERENA_MCP_HOST=0.0.0.0
      - MCP_SERVER_STDIO=true
      - MCP_DEBUG_PORT=${MCP_DEBUG_PORT:-9229}

      # User-specific environment variables
      - GIT_USER_NAME=${GIT_USER_NAME:-developer}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-developer@example.com}

      # Additional MCP configuration
      - MCP_CONFIG_PATH=/workspace/.devcontainer/override_files/mcp-config.json
      - CLAUDE_MCP_CONFIG=/workspace/.devcontainer/override_files/mcp-config.json

      # npm global PATH and uv PATH
      - PATH=/home/node/.local/bin:/home/node/.npm-global/bin:$PATH

    volumes:
      # Mount user-specific configuration directories
      - ${HOME}/.claude:/home/node/.claude:cached
      - ${HOME}/.serena:/home/node/.serena:cached
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - ${HOME}/.gitconfig:/home/node/.gitconfig:ro

      # Mount override files
      - ./override_files:/workspace/.devcontainer/override_files:cached

      # User workspace cache
      - ${HOME}/.cache:/home/node/.cache:cached

    # Additional ports for MCP servers
    # Note: ports are ignored when using network_mode: host
    # The services will be accessible on localhost at their respective ports
